syntax = "proto3";

package stockstore.v1;
option go_package = "stocker-store/proto/v1;stockstorev1";

service StockStore {
	rpc AddStocks(stream UpdateStockRequest) returns (Stock);
	rpc UpdateStock(UpdateStockRequest) returns (Stock);
	rpc RemoveStock(RemoveStockRequest) returns (RemoveStockResponse);
	rpc GetStock(GetStockRequest) returns (Stock);
	rpc GetStocks(GetStocksRequest) returns (StockList);
}

message UpdateStockRequest { string symbol = 1; string exchange = 2; optional map<string, double> scores = 3; }
message RemoveStockRequest { string symbol = 1; string exchange = 2; }
message GetStockRequest { string symbol = 1; optional string exchange = 2; }
message GetStocksRequest { int32 limit = 1; optional string exchange = 2; optional map<string, double> min_scores = 3; optional map<string, double> max_scores = 4; }
message RemoveStockResponse { bool removed = 1; }
message Stock { string symbol = 1; string exchange = 2; repeated ScoreEntry scores = 3; }
message ScoreEntry { string category = 1; double value = 2; }
message StockList { repeated Stock stocks = 1; }
