// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.27.2
// source: proto/v1/stock_store.proto

package stockstorev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StockStore_AddStocks_FullMethodName   = "/stockstore.v1.StockStore/AddStocks"
	StockStore_UpdateStock_FullMethodName = "/stockstore.v1.StockStore/UpdateStock"
	StockStore_RemoveStock_FullMethodName = "/stockstore.v1.StockStore/RemoveStock"
	StockStore_GetStock_FullMethodName    = "/stockstore.v1.StockStore/GetStock"
	StockStore_GetStocks_FullMethodName   = "/stockstore.v1.StockStore/GetStocks"
)

// StockStoreClient is the client API for StockStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StockStoreClient interface {
	AddStocks(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UpdateStockRequest, Stock], error)
	UpdateStock(ctx context.Context, in *UpdateStockRequest, opts ...grpc.CallOption) (*Stock, error)
	RemoveStock(ctx context.Context, in *RemoveStockRequest, opts ...grpc.CallOption) (*RemoveStockResponse, error)
	GetStock(ctx context.Context, in *GetStockRequest, opts ...grpc.CallOption) (*Stock, error)
	GetStocks(ctx context.Context, in *GetStocksRequest, opts ...grpc.CallOption) (*StockList, error)
}

type stockStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewStockStoreClient(cc grpc.ClientConnInterface) StockStoreClient {
	return &stockStoreClient{cc}
}

func (c *stockStoreClient) AddStocks(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UpdateStockRequest, Stock], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StockStore_ServiceDesc.Streams[0], StockStore_AddStocks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UpdateStockRequest, Stock]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StockStore_AddStocksClient = grpc.ClientStreamingClient[UpdateStockRequest, Stock]

func (c *stockStoreClient) UpdateStock(ctx context.Context, in *UpdateStockRequest, opts ...grpc.CallOption) (*Stock, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Stock)
	err := c.cc.Invoke(ctx, StockStore_UpdateStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockStoreClient) RemoveStock(ctx context.Context, in *RemoveStockRequest, opts ...grpc.CallOption) (*RemoveStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveStockResponse)
	err := c.cc.Invoke(ctx, StockStore_RemoveStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockStoreClient) GetStock(ctx context.Context, in *GetStockRequest, opts ...grpc.CallOption) (*Stock, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Stock)
	err := c.cc.Invoke(ctx, StockStore_GetStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockStoreClient) GetStocks(ctx context.Context, in *GetStocksRequest, opts ...grpc.CallOption) (*StockList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockList)
	err := c.cc.Invoke(ctx, StockStore_GetStocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StockStoreServer is the server API for StockStore service.
// All implementations must embed UnimplementedStockStoreServer
// for forward compatibility.
type StockStoreServer interface {
	AddStocks(grpc.ClientStreamingServer[UpdateStockRequest, Stock]) error
	UpdateStock(context.Context, *UpdateStockRequest) (*Stock, error)
	RemoveStock(context.Context, *RemoveStockRequest) (*RemoveStockResponse, error)
	GetStock(context.Context, *GetStockRequest) (*Stock, error)
	GetStocks(context.Context, *GetStocksRequest) (*StockList, error)
	mustEmbedUnimplementedStockStoreServer()
}

// UnimplementedStockStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStockStoreServer struct{}

func (UnimplementedStockStoreServer) AddStocks(grpc.ClientStreamingServer[UpdateStockRequest, Stock]) error {
	return status.Error(codes.Unimplemented, "method AddStocks not implemented")
}
func (UnimplementedStockStoreServer) UpdateStock(context.Context, *UpdateStockRequest) (*Stock, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStock not implemented")
}
func (UnimplementedStockStoreServer) RemoveStock(context.Context, *RemoveStockRequest) (*RemoveStockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveStock not implemented")
}
func (UnimplementedStockStoreServer) GetStock(context.Context, *GetStockRequest) (*Stock, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStock not implemented")
}
func (UnimplementedStockStoreServer) GetStocks(context.Context, *GetStocksRequest) (*StockList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStocks not implemented")
}
func (UnimplementedStockStoreServer) mustEmbedUnimplementedStockStoreServer() {}
func (UnimplementedStockStoreServer) testEmbeddedByValue()                    {}

// UnsafeStockStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StockStoreServer will
// result in compilation errors.
type UnsafeStockStoreServer interface {
	mustEmbedUnimplementedStockStoreServer()
}

func RegisterStockStoreServer(s grpc.ServiceRegistrar, srv StockStoreServer) {
	// If the following call panics, it indicates UnimplementedStockStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StockStore_ServiceDesc, srv)
}

func _StockStore_AddStocks_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StockStoreServer).AddStocks(&grpc.GenericServerStream[UpdateStockRequest, Stock]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StockStore_AddStocksServer = grpc.ClientStreamingServer[UpdateStockRequest, Stock]

func _StockStore_UpdateStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockStoreServer).UpdateStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockStore_UpdateStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockStoreServer).UpdateStock(ctx, req.(*UpdateStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockStore_RemoveStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockStoreServer).RemoveStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockStore_RemoveStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockStoreServer).RemoveStock(ctx, req.(*RemoveStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockStore_GetStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockStoreServer).GetStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockStore_GetStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockStoreServer).GetStock(ctx, req.(*GetStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockStore_GetStocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockStoreServer).GetStocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockStore_GetStocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockStoreServer).GetStocks(ctx, req.(*GetStocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StockStore_ServiceDesc is the grpc.ServiceDesc for StockStore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StockStore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stockstore.v1.StockStore",
	HandlerType: (*StockStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateStock",
			Handler:    _StockStore_UpdateStock_Handler,
		},
		{
			MethodName: "RemoveStock",
			Handler:    _StockStore_RemoveStock_Handler,
		},
		{
			MethodName: "GetStock",
			Handler:    _StockStore_GetStock_Handler,
		},
		{
			MethodName: "GetStocks",
			Handler:    _StockStore_GetStocks_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AddStocks",
			Handler:       _StockStore_AddStocks_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/v1/stock_store.proto",
}
