// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: proto/v1/stock_store.proto

package stockstorev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Exchange      string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Scores        map[string]float64     `protobuf:"bytes,3,rep,name=scores,proto3" json:"scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockRequest) Reset() {
	*x = UpdateStockRequest{}
	mi := &file_proto_v1_stock_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockRequest) ProtoMessage() {}

func (x *UpdateStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_stock_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockRequest.ProtoReflect.Descriptor instead.
func (*UpdateStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_stock_store_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateStockRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *UpdateStockRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *UpdateStockRequest) GetScores() map[string]float64 {
	if x != nil {
		return x.Scores
	}
	return nil
}

type RemoveStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Exchange      string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveStockRequest) Reset() {
	*x = RemoveStockRequest{}
	mi := &file_proto_v1_stock_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveStockRequest) ProtoMessage() {}

func (x *RemoveStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_stock_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveStockRequest.ProtoReflect.Descriptor instead.
func (*RemoveStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_stock_store_proto_rawDescGZIP(), []int{1}
}

func (x *RemoveStockRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *RemoveStockRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

type GetStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Exchange      *string                `protobuf:"bytes,2,opt,name=exchange,proto3,oneof" json:"exchange,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockRequest) Reset() {
	*x = GetStockRequest{}
	mi := &file_proto_v1_stock_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockRequest) ProtoMessage() {}

func (x *GetStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_stock_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockRequest.ProtoReflect.Descriptor instead.
func (*GetStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_stock_store_proto_rawDescGZIP(), []int{2}
}

func (x *GetStockRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetStockRequest) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

type GetStocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Exchange      *string                `protobuf:"bytes,2,opt,name=exchange,proto3,oneof" json:"exchange,omitempty"`
	MinScores     map[string]float64     `protobuf:"bytes,3,rep,name=min_scores,json=minScores,proto3" json:"min_scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	MaxScores     map[string]float64     `protobuf:"bytes,4,rep,name=max_scores,json=maxScores,proto3" json:"max_scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStocksRequest) Reset() {
	*x = GetStocksRequest{}
	mi := &file_proto_v1_stock_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStocksRequest) ProtoMessage() {}

func (x *GetStocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_stock_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStocksRequest.ProtoReflect.Descriptor instead.
func (*GetStocksRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_stock_store_proto_rawDescGZIP(), []int{3}
}

func (x *GetStocksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetStocksRequest) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *GetStocksRequest) GetMinScores() map[string]float64 {
	if x != nil {
		return x.MinScores
	}
	return nil
}

func (x *GetStocksRequest) GetMaxScores() map[string]float64 {
	if x != nil {
		return x.MaxScores
	}
	return nil
}

type RemoveStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       bool                   `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveStockResponse) Reset() {
	*x = RemoveStockResponse{}
	mi := &file_proto_v1_stock_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveStockResponse) ProtoMessage() {}

func (x *RemoveStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_stock_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveStockResponse.ProtoReflect.Descriptor instead.
func (*RemoveStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_stock_store_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveStockResponse) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

type Stock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Exchange      string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Scores        []*ScoreEntry          `protobuf:"bytes,3,rep,name=scores,proto3" json:"scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stock) Reset() {
	*x = Stock{}
	mi := &file_proto_v1_stock_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stock) ProtoMessage() {}

func (x *Stock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_stock_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stock.ProtoReflect.Descriptor instead.
func (*Stock) Descriptor() ([]byte, []int) {
	return file_proto_v1_stock_store_proto_rawDescGZIP(), []int{5}
}

func (x *Stock) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Stock) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Stock) GetScores() []*ScoreEntry {
	if x != nil {
		return x.Scores
	}
	return nil
}

type ScoreEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreEntry) Reset() {
	*x = ScoreEntry{}
	mi := &file_proto_v1_stock_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreEntry) ProtoMessage() {}

func (x *ScoreEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_stock_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreEntry.ProtoReflect.Descriptor instead.
func (*ScoreEntry) Descriptor() ([]byte, []int) {
	return file_proto_v1_stock_store_proto_rawDescGZIP(), []int{6}
}

func (x *ScoreEntry) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ScoreEntry) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ScoreEntry) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type StockList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stocks        []*Stock               `protobuf:"bytes,1,rep,name=stocks,proto3" json:"stocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockList) Reset() {
	*x = StockList{}
	mi := &file_proto_v1_stock_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockList) ProtoMessage() {}

func (x *StockList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_stock_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockList.ProtoReflect.Descriptor instead.
func (*StockList) Descriptor() ([]byte, []int) {
	return file_proto_v1_stock_store_proto_rawDescGZIP(), []int{7}
}

func (x *StockList) GetStocks() []*Stock {
	if x != nil {
		return x.Stocks
	}
	return nil
}

var File_proto_v1_stock_store_proto protoreflect.FileDescriptor

const file_proto_v1_stock_store_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/v1/stock_store.proto\x12\rstockstore.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xca\x01\n" +
	"\x12UpdateStockRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x12E\n" +
	"\x06scores\x18\x03 \x03(\v2-.stockstore.v1.UpdateStockRequest.ScoresEntryR\x06scores\x1a9\n" +
	"\vScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"H\n" +
	"\x12RemoveStockRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\"W\n" +
	"\x0fGetStockRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1f\n" +
	"\bexchange\x18\x02 \x01(\tH\x00R\bexchange\x88\x01\x01B\v\n" +
	"\t_exchange\"\xf0\x02\n" +
	"\x10GetStocksRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x1f\n" +
	"\bexchange\x18\x02 \x01(\tH\x00R\bexchange\x88\x01\x01\x12M\n" +
	"\n" +
	"min_scores\x18\x03 \x03(\v2..stockstore.v1.GetStocksRequest.MinScoresEntryR\tminScores\x12M\n" +
	"\n" +
	"max_scores\x18\x04 \x03(\v2..stockstore.v1.GetStocksRequest.MaxScoresEntryR\tmaxScores\x1a<\n" +
	"\x0eMinScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a<\n" +
	"\x0eMaxScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01B\v\n" +
	"\t_exchange\"/\n" +
	"\x13RemoveStockResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\bR\aremoved\"n\n" +
	"\x05Stock\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x121\n" +
	"\x06scores\x18\x03 \x03(\v2\x19.stockstore.v1.ScoreEntryR\x06scores\"y\n" +
	"\n" +
	"ScoreEntry\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"9\n" +
	"\tStockList\x12,\n" +
	"\x06stocks\x18\x01 \x03(\v2\x14.stockstore.v1.StockR\x06stocks2\xfc\x02\n" +
	"\n" +
	"StockStore\x12F\n" +
	"\tAddStocks\x12!.stockstore.v1.UpdateStockRequest\x1a\x14.stockstore.v1.Stock(\x01\x12F\n" +
	"\vUpdateStock\x12!.stockstore.v1.UpdateStockRequest\x1a\x14.stockstore.v1.Stock\x12T\n" +
	"\vRemoveStock\x12!.stockstore.v1.RemoveStockRequest\x1a\".stockstore.v1.RemoveStockResponse\x12@\n" +
	"\bGetStock\x12\x1e.stockstore.v1.GetStockRequest\x1a\x14.stockstore.v1.Stock\x12F\n" +
	"\tGetStocks\x12\x1f.stockstore.v1.GetStocksRequest\x1a\x18.stockstore.v1.StockListB%Z#stocker-store/proto/v1;stockstorev1b\x06proto3"

var (
	file_proto_v1_stock_store_proto_rawDescOnce sync.Once
	file_proto_v1_stock_store_proto_rawDescData []byte
)

func file_proto_v1_stock_store_proto_rawDescGZIP() []byte {
	file_proto_v1_stock_store_proto_rawDescOnce.Do(func() {
		file_proto_v1_stock_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_stock_store_proto_rawDesc), len(file_proto_v1_stock_store_proto_rawDesc)))
	})
	return file_proto_v1_stock_store_proto_rawDescData
}

var file_proto_v1_stock_store_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_v1_stock_store_proto_goTypes = []any{
	(*UpdateStockRequest)(nil),    // 0: stockstore.v1.UpdateStockRequest
	(*RemoveStockRequest)(nil),    // 1: stockstore.v1.RemoveStockRequest
	(*GetStockRequest)(nil),       // 2: stockstore.v1.GetStockRequest
	(*GetStocksRequest)(nil),      // 3: stockstore.v1.GetStocksRequest
	(*RemoveStockResponse)(nil),   // 4: stockstore.v1.RemoveStockResponse
	(*Stock)(nil),                 // 5: stockstore.v1.Stock
	(*ScoreEntry)(nil),            // 6: stockstore.v1.ScoreEntry
	(*StockList)(nil),             // 7: stockstore.v1.StockList
	nil,                           // 8: stockstore.v1.UpdateStockRequest.ScoresEntry
	nil,                           // 9: stockstore.v1.GetStocksRequest.MinScoresEntry
	nil,                           // 10: stockstore.v1.GetStocksRequest.MaxScoresEntry
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_proto_v1_stock_store_proto_depIdxs = []int32{
	8,  // 0: stockstore.v1.UpdateStockRequest.scores:type_name -> stockstore.v1.UpdateStockRequest.ScoresEntry
	9,  // 1: stockstore.v1.GetStocksRequest.min_scores:type_name -> stockstore.v1.GetStocksRequest.MinScoresEntry
	10, // 2: stockstore.v1.GetStocksRequest.max_scores:type_name -> stockstore.v1.GetStocksRequest.MaxScoresEntry
	6,  // 3: stockstore.v1.Stock.scores:type_name -> stockstore.v1.ScoreEntry
	11, // 4: stockstore.v1.ScoreEntry.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 5: stockstore.v1.StockList.stocks:type_name -> stockstore.v1.Stock
	0,  // 6: stockstore.v1.StockStore.AddStocks:input_type -> stockstore.v1.UpdateStockRequest
	0,  // 7: stockstore.v1.StockStore.UpdateStock:input_type -> stockstore.v1.UpdateStockRequest
	1,  // 8: stockstore.v1.StockStore.RemoveStock:input_type -> stockstore.v1.RemoveStockRequest
	2,  // 9: stockstore.v1.StockStore.GetStock:input_type -> stockstore.v1.GetStockRequest
	3,  // 10: stockstore.v1.StockStore.GetStocks:input_type -> stockstore.v1.GetStocksRequest
	5,  // 11: stockstore.v1.StockStore.AddStocks:output_type -> stockstore.v1.Stock
	5,  // 12: stockstore.v1.StockStore.UpdateStock:output_type -> stockstore.v1.Stock
	4,  // 13: stockstore.v1.StockStore.RemoveStock:output_type -> stockstore.v1.RemoveStockResponse
	5,  // 14: stockstore.v1.StockStore.GetStock:output_type -> stockstore.v1.Stock
	7,  // 15: stockstore.v1.StockStore.GetStocks:output_type -> stockstore.v1.StockList
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_v1_stock_store_proto_init() }
func file_proto_v1_stock_store_proto_init() {
	if File_proto_v1_stock_store_proto != nil {
		return
	}
	file_proto_v1_stock_store_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_v1_stock_store_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_stock_store_proto_rawDesc), len(file_proto_v1_stock_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_stock_store_proto_goTypes,
		DependencyIndexes: file_proto_v1_stock_store_proto_depIdxs,
		MessageInfos:      file_proto_v1_stock_store_proto_msgTypes,
	}.Build()
	File_proto_v1_stock_store_proto = out.File
	file_proto_v1_stock_store_proto_goTypes = nil
	file_proto_v1_stock_store_proto_depIdxs = nil
}
