// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.27.2
// source: proto/v1/kafka/stock_message.proto

package kafkastockv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StockUpdate carries a stock symbol, its exchange, and optional score
// entries. This is the message format published to (and consumed from) kafka
// topics by external scoring services.
type StockUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Exchange      string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Scores        map[string]float64     `protobuf:"bytes,3,rep,name=scores,proto3" json:"scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockUpdate) Reset() {
	*x = StockUpdate{}
	mi := &file_proto_v1_kafka_stock_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockUpdate) ProtoMessage() {}

func (x *StockUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_kafka_stock_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockUpdate.ProtoReflect.Descriptor instead.
func (*StockUpdate) Descriptor() ([]byte, []int) {
	return file_proto_v1_kafka_stock_message_proto_rawDescGZIP(), []int{0}
}

func (x *StockUpdate) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *StockUpdate) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *StockUpdate) GetScores() map[string]float64 {
	if x != nil {
		return x.Scores
	}
	return nil
}

var File_proto_v1_kafka_stock_message_proto protoreflect.FileDescriptor

const file_proto_v1_kafka_stock_message_proto_rawDesc = "" +
	"\n" +
	"\"proto/v1/kafka/stock_message.proto\x12\x15stockerstore.kafka.v1\"\xc4\x01\n" +
	"\vStockUpdate\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x12F\n" +
	"\x06scores\x18\x03 \x03(\v2..stockerstore.kafka.v1.StockUpdate.ScoresEntryR\x06scores\x1a9\n" +
	"\vScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01B+Z)stocker-store/proto/v1/kafka;kafkastockv1b\x06proto3"

var (
	file_proto_v1_kafka_stock_message_proto_rawDescOnce sync.Once
	file_proto_v1_kafka_stock_message_proto_rawDescData []byte
)

func file_proto_v1_kafka_stock_message_proto_rawDescGZIP() []byte {
	file_proto_v1_kafka_stock_message_proto_rawDescOnce.Do(func() {
		file_proto_v1_kafka_stock_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_kafka_stock_message_proto_rawDesc), len(file_proto_v1_kafka_stock_message_proto_rawDesc)))
	})
	return file_proto_v1_kafka_stock_message_proto_rawDescData
}

var file_proto_v1_kafka_stock_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_v1_kafka_stock_message_proto_goTypes = []any{
	(*StockUpdate)(nil), // 0: stockerstore.kafka.v1.StockUpdate
	nil,                 // 1: stockerstore.kafka.v1.StockUpdate.ScoresEntry
}
var file_proto_v1_kafka_stock_message_proto_depIdxs = []int32{
	1, // 0: stockerstore.kafka.v1.StockUpdate.scores:type_name -> stockerstore.kafka.v1.StockUpdate.ScoresEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_v1_kafka_stock_message_proto_init() }
func file_proto_v1_kafka_stock_message_proto_init() {
	if File_proto_v1_kafka_stock_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_kafka_stock_message_proto_rawDesc), len(file_proto_v1_kafka_stock_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_kafka_stock_message_proto_goTypes,
		DependencyIndexes: file_proto_v1_kafka_stock_message_proto_depIdxs,
		MessageInfos:      file_proto_v1_kafka_stock_message_proto_msgTypes,
	}.Build()
	File_proto_v1_kafka_stock_message_proto = out.File
	file_proto_v1_kafka_stock_message_proto_goTypes = nil
	file_proto_v1_kafka_stock_message_proto_depIdxs = nil
}
