// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: proto/v1/kafka/stock_message.proto

package kafkastockv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ScoreEntry carries a single score category, its value, and the time it was
// last updated. Field numbers and types mirror the gRPC ScoreEntry in
// stockstore.v1 for shape parity.
type ScoreEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreEntry) Reset() {
	*x = ScoreEntry{}
	mi := &file_proto_v1_kafka_stock_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreEntry) ProtoMessage() {}

func (x *ScoreEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_kafka_stock_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreEntry.ProtoReflect.Descriptor instead.
func (*ScoreEntry) Descriptor() ([]byte, []int) {
	return file_proto_v1_kafka_stock_message_proto_rawDescGZIP(), []int{0}
}

func (x *ScoreEntry) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ScoreEntry) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ScoreEntry) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// StockUpdate carries a stock symbol, its exchange, and a set of scores,
// each as a ScoreEntry with its own per-entry updated_at timestamp. This is
// the message format published to (and consumed from) kafka topics by
// external scoring services.
type StockUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Exchange      string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Scores        []*ScoreEntry          `protobuf:"bytes,3,rep,name=scores,proto3" json:"scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockUpdate) Reset() {
	*x = StockUpdate{}
	mi := &file_proto_v1_kafka_stock_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockUpdate) ProtoMessage() {}

func (x *StockUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_kafka_stock_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockUpdate.ProtoReflect.Descriptor instead.
func (*StockUpdate) Descriptor() ([]byte, []int) {
	return file_proto_v1_kafka_stock_message_proto_rawDescGZIP(), []int{1}
}

func (x *StockUpdate) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *StockUpdate) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *StockUpdate) GetScores() []*ScoreEntry {
	if x != nil {
		return x.Scores
	}
	return nil
}

var File_proto_v1_kafka_stock_message_proto protoreflect.FileDescriptor

const file_proto_v1_kafka_stock_message_proto_rawDesc = "" +
	"\n" +
	"\"proto/v1/kafka/stock_message.proto\x12\x15stockerstore.kafka.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"y\n" +
	"\n" +
	"ScoreEntry\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"|\n" +
	"\vStockUpdate\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x129\n" +
	"\x06scores\x18\x03 \x03(\v2!.stockerstore.kafka.v1.ScoreEntryR\x06scoresB+Z)stocker-store/proto/v1/kafka;kafkastockv1b\x06proto3"

var (
	file_proto_v1_kafka_stock_message_proto_rawDescOnce sync.Once
	file_proto_v1_kafka_stock_message_proto_rawDescData []byte
)

func file_proto_v1_kafka_stock_message_proto_rawDescGZIP() []byte {
	file_proto_v1_kafka_stock_message_proto_rawDescOnce.Do(func() {
		file_proto_v1_kafka_stock_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_kafka_stock_message_proto_rawDesc), len(file_proto_v1_kafka_stock_message_proto_rawDesc)))
	})
	return file_proto_v1_kafka_stock_message_proto_rawDescData
}

var file_proto_v1_kafka_stock_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_v1_kafka_stock_message_proto_goTypes = []any{
	(*ScoreEntry)(nil),            // 0: stockerstore.kafka.v1.ScoreEntry
	(*StockUpdate)(nil),           // 1: stockerstore.kafka.v1.StockUpdate
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_proto_v1_kafka_stock_message_proto_depIdxs = []int32{
	2, // 0: stockerstore.kafka.v1.ScoreEntry.updated_at:type_name -> google.protobuf.Timestamp
	0, // 1: stockerstore.kafka.v1.StockUpdate.scores:type_name -> stockerstore.kafka.v1.ScoreEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_v1_kafka_stock_message_proto_init() }
func file_proto_v1_kafka_stock_message_proto_init() {
	if File_proto_v1_kafka_stock_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_kafka_stock_message_proto_rawDesc), len(file_proto_v1_kafka_stock_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_kafka_stock_message_proto_goTypes,
		DependencyIndexes: file_proto_v1_kafka_stock_message_proto_depIdxs,
		MessageInfos:      file_proto_v1_kafka_stock_message_proto_msgTypes,
	}.Build()
	File_proto_v1_kafka_stock_message_proto = out.File
	file_proto_v1_kafka_stock_message_proto_goTypes = nil
	file_proto_v1_kafka_stock_message_proto_depIdxs = nil
}
